### ISSUE TITLE
pyocd支持：ValueError: invalid literal for int() with base 10: 'v6'

### ISSUE THREAD

**Issue by driftregion** [wuxx/nanoDAP-HS-wireless#2]
用pyocd我遇到了下面问题：

```sh
> pyocd --version 
0.30.4.dev30
```

```
> pyocd gdbserver --persist  --config pyocd_hc32.yaml                                                                                           0
0000804:INFO:session:Using config settings for probe 1101368250203220304b4a57323038203432303097969903
['v6', '1e-113008-15035']
0000818:CRITICAL:__main__:invalid literal for int() with base 10: 'v6'
Traceback (most recent call last):
  File "/home/user/repos/pyOCD/pyocd/__main__.py", line 150, in run
    status = cmd.invoke()
  File "/home/user/repos/pyOCD/pyocd/subcommands/gdbserver_cmd.py", line 190, in invoke
    with session:
  File "/home/user/repos/pyOCD/pyocd/core/session.py", line 343, in __enter__
    self.open()
  File "/home/user/repos/pyOCD/pyocd/core/session.py", line 457, in open
    self._probe.open()
  File "/home/user/repos/pyOCD/pyocd/probe/shared_probe_proxy.py", line 55, in open
    self._probe.open()
  File "/home/user/repos/pyOCD/pyocd/probe/cmsis_dap_probe.py", line 170, in open
    self._link.open()
  File "/home/user/repos/pyOCD/pyocd/utility/concurrency.py", line 28, in _locking
    return func(self, *args, **kwargs)
  File "/home/user/repos/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 645, in open
    self._read_protocol_version()
  File "/home/user/repos/pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py", line 617, in _read_protocol_version
    major = int(fw_version[0])
ValueError: invalid literal for int() with base 10: 'v6'
```

`pyOCD/pyocd/probe/pydapaccess/dap_access_cmsis_dap.py:597`

```py
    def _read_protocol_version(self):
        """! Determine the CMSIS-DAP protocol version."""
        fw_version_str = self._protocol.dap_info(self.ID.FW_VER)
        # Just in case we don't get a valid response, default to the lowest version (not including betas).
        if not fw_version_str:
            self._cmsis_dap_version = CMSISDAPVersion.V1_0_0
        # Deal with DAPLink broken version number, where these versions of the firmware reported the DAPLink
        # version number for DAP_INFO_FW_VER instead of the CMSIS-DAP version, due to a misunderstanding
        # based on unclear documentation.
        elif (self._vidpid == ARM_DAPLINK_ID) and (fw_version_str in ("0254", "0255", "0256")):
            self._cmsis_dap_version = CMSISDAPVersion.V2_0_0
        else:
            # Convert the version to a single BCD value for easy comparison.
            # 1.2.3 will be converted to 0x10203, 1.10 to 0x11000, and so on.
            #
            # There are two version formats returned from the reference CMSIS-DAP code: 2-field and 3-field.
            # The older versions return versions like "1.07" and "1.10", while recent versions return "1.2.0"
            # or "2.0.0".
            fw_version = fw_version_str.split('.')
            print(fw_version)
            major = int(fw_version[0])
            # Handle version of the form "1.10" by treating the two digits after the dot as minor and patch.
            if (len(fw_version) == 2) and len(fw_version[1]) == 2:
                minor = int(fw_version[1][0])
                patch = int(fw_version[1][1])
            # All other forms, including unexpected cases such as 
            else:
                minor = int(fw_version[1] if len(fw_version) > 1 else 0)
                patch = int(fw_version[2] if len(fw_version) > 2 else 0)
            self._cmsis_dap_version = (major, minor, patch)

        # Log probe's protocol version.
        LOG.debug("CMSIS-DAP probe %s protocol version: %i.%i.%i", self._unique_id, *self._cmsis_dap_version)

```

在`else`里面直接设置一个CMSIS-DAP版本就可以正常使用。
```py
            self._cmsis_dap_version = CMSISDAPVersion.V2_0_0
            return
```

好想pyocd支持的版本字符串格式和nanoDAP目前的版本字符串不兼容：
['v6', '1e-113008-15035']

谢谢、这个调试器好用。

**Comment by wuxx** [comment]
好的
